import type { BlogPost } from "../types"

const post: BlogPost = {
  slug: "abdullahalnahid-issutmkl-VP",
  title: "Media Recognition - ISS UTMKL VP Election",
  date: "30 November 2025",
  image: new URL(
    "../../../assets/abdullahalnahid-issutmkl-VP.png",
    import.meta.url
  ).href,
  content: `
    <p>Following my election as VP of the International Student Society (ISS UTMKL), the response from the media has been overwhelming. I am profoundly grateful for the thoughtful coverage provided by over 15 national and international outlets, including leading voices such as NTV, Somoy News, and Jugantor.</p>

    <p>Journalism plays a vital role in amplifying student voices and giving visibility to international leadership. The attention generated by this coverage has significantly reinforced my platform, empowering me to advocate even more confidently for the needs of our diverse student body.</p>

    <p>Thank you to every reporter and editor who dedicated time and professionalism to share this story. Your work is a testament to the importance of promoting positive youth leadership and cross-cultural dialogue.</p>

    <p>I will continue to bring the policy-driven focus of the ISAP panel, backed by this incredible visibility, into action.</p>

    <h3>Reference:</h3>
    <ol>
      <li><a href="https://ntvbd.com/education/news-1653801" target="_blank">ntvbd.com/education/news-1653801</a></li>
      <li><a href="https://www.somoynews.tv/news/2025-11-24/Lu027AZW" target="_blank">somoynews.tv/news/2025-11-24/Lu027AZW</a></li>
      <li><a href="https://www.jagonews24.com/m/probash/article/1070765" target="_blank">jagonews24.com/m/probash/article/1070765</a></li>
      <li><a href="https://www.jugantor.com/campus/1033165" target="_blank">jugantor.com/campus/1033165</a></li>
      <li><a href="https://barta24.com/details/immigrant/301858" target="_blank">barta24.com/details/immigrant/301858</a></li>
      <li><a href="https://www.bahannonews.com/details/article/10182181" target="_blank">bahannonews.com/details/article/10182181</a></li>
      <li><a href="https://www.probashirkotha.com/2025/11/25/মালয়েশিয়ার-শীর্ষ-বিশ্ব/" target="_blank">probasirkotha.com</a></li>
      <li><a href="https://www.dailybhoreralo.com/Education-news/4058" target="_blank">dailybhoreralo.com/Education-news/4058</a></li>
      <li><a href="https://probashtime.net/asia/malaysia/135284/" target="_blank">probashtime.net/asia/malaysia/135284</a></li>
    </ol>

    <p>#ThankYou #Journalism #MediaRecognition #UTMKL #StudentLeadership #Bangladesh #InternationalAffairs</p>
  `
}

export default post